apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notes-api.fullname" . }}
  labels: {{- include "notes-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- if .Values.persistence.enabled }}
  strategy:
    type: Recreate   # ReadWriteOnce volume
  {{- end }}
  selector:
    matchLabels: {{- include "notes-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "notes-api.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ toYaml .Values.config | sha256sum }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile: { type: RuntimeDefault }
      containers:
        - name: notes-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - configMapRef: { name: {{ include "notes-api.fullname" . }} }
            - secretRef: { name: {{ include "notes-api.secretName" . }} }
          startupProbe:
            httpGet: { path: /healthz, port: http }
            failureThreshold: 20
            periodSeconds: 2
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            periodSeconds: 10
          readinessProbe:
            httpGet: { path: /readyz, port: http }
            periodSeconds: 5
          resources: {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }
          volumeMounts:
            - { name: data, mountPath: /data }
            - { name: tmp, mountPath: /tmp }
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim: { claimName: {{ include "notes-api.fullname" . }}-data }
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: tmp
          emptyDir: {}
