{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notes-api.fullname" . }}
  labels: {{- include "notes-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEY: {{ .Values.secret.apiKey | quote }}
{{- end }}
