{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "notes-api.fullname" . }}
  labels:
    {{- include "notes-api.labels" . | nindent 4 }}
    release: monitoring   # must match the Prometheus Operator's serviceMonitorSelector
spec:
  selector:
    matchLabels: {{- include "notes-api.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
{{- end }}
