apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: icms-lab
data:
  APP_ENV: "production"
  APP_COLOR: "blue"
  APP_GREETING: "Hello from ConfigMap"
  config.properties: |
    log.level=INFO
    cache.enabled=true
