apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops-demo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/YOUR_USER/YOUR_CONFIG_REPO.git # <-- change me
  ref:
    branch: main
